qt: Avoid X11 / QT symbols clashing
The X11 library defines into the X11/X.h include file the following symbols by means of #define:

- CursorShape
- Bool
- Status
- None
- KeyPress
- KeyRelease
- FocusIn
- FocusOut
- FontChange
- Expose
(and more)

The same symbols are also used by Qt library (see qt5/QtCore/qcoreevent.h incldue file) and including X11 files before Qt includes will generate a lot of symbol name collisions with strange compiler
errors like:

/usr/include/qt5/QtCore/qcoreevent.h:63:9: error: expected identifier before numeric constant
         None = 0,                               // invalid event
         ^

To solve this kind of issue we must #undef all clashing X11 symbols before to include Qt files.

Plex-CLA-1.0-signed-off-by: Luigi Mantellini <luigi.mantellini@gmail.com>